- name: Install Xorg and tools
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit

- name: Install Nvidia
  become: yes
  pacman: name=nvidia-340xx-utils

- name: Install Plasma KDE
  become: yes
  pacman: name=plasma-desktop

- name: Install KDE tools
  become: yes
  pacman:
    name:
      - plasma-pa
      - powerdevil
      - kscreen
